# Generated by Django 4.2.1 on 2023-06-12 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="usuario",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="core.usuario",
            ),
            preserve_default=False,
        ),
    ]
