# Generated by Django 4.2.1 on 2023-06-19 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_post_usuario"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="usuario",),
    ]
