# Generated by Django 4.2.1 on 2023-06-19 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_post_usuario"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post", old_name="corpo", new_name="descricao",
        ),
        migrations.RenameField(model_name="post", old_name="titulo", new_name="nome",),
    ]
