# Generated by Django 4.2.1 on 2023-06-19 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_rename_corpo_post_descricao_rename_titulo_post_nome"),
    ]

    operations = [
        migrations.RenameModel(old_name="Post", new_name="Tarefa",),
    ]
