# Generated by Django 4.2.1 on 2023-06-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_rename_post_tarefa"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarefa",
            name="concluido",
            field=models.BooleanField(default=False),
        ),
    ]
