# Generated by Django 4.2.1 on 2023-07-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_tarefa_concluido"),
    ]

    operations = [
        migrations.DeleteModel(name="Usuario",),
        migrations.AlterField(
            model_name="tarefa",
            name="descricao",
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
