# Generated by Django 4.2.6 on 2023-10-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_usuario_alter_tarefa_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='qtd_rounds',
            field=models.IntegerField(default=0),
        ),
    ]
