# Generated by Django 4.2.6 on 2023-11-01 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tarefa_qtd_rounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='data_conclusao',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='data_criacao',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
